### ISSUE TITLE
issue#4 實作2_主從結構MASTER/DETAIL

### ISSUE THREAD

**Issue by ChuangPoPO** [ChuangPoPO/JS_Angular2#4]
開一個新的 branch : issue#4
練習 <英雄指南> 的實作2_主從結構MASTER/DETAIL

**Comment by ChuangPoPO** [comment]
已新開branch : issue#4

**Comment by ChuangPoPO** [comment]
2016/12/17(六)
在li 中使用 `*ngFor = "let hero of heroes"` 列出 heroes 矩陣。

2016/12/24(六)
Click event：
在 li 中加入 `(click)="onSelect(hero)"` ，hero 即 ngFor 所定義的。
binding 的依據是 onSelect() method

Add the click handler：
在 ` AppComponent ` 加入 onSelect() method

使用 `[(ngModel)]`：來綁定雙向資料

使用 `*ngIf` ：在條件成立(truthy)時，才會顯示資訊。

` [class.selected]="hero === selectedHero"` ：在`" "`內成立(truthy)時，套用 `selected` 

` [class.selected]` ：class biding，用於新增或移除單一個css class；若同時有多個css 需要更換，則需要使用 ngClass。 

---
`:` ：後面放的是屬性
`=` ：後面是要assign的值

`===`：物件間的比較
`==`：基本型態間的比較(比記憶體位置)

**Comment by Gaduo** [comment]
#5

**Comment by ChuangPoPO** [comment]
```<button (click)="onClickMe()">Click me!</button>```
`(click)` 綁定目標
`"onClickMe()"`為 method方法，作為回應`(click)`event事件

**Comment by ChuangPoPO** [comment]
[Property]屬性、[Attribute]屬性、[Class]類別、[Style]css
ex. `[src]`.`[ngClass]`.`[hero]`.....
ex. `[attr.aria-label]="help"`
ex. `[class.special]="isSpecial"`
ex. `[style.color]="isSpecial?'red' : 'green' "`

(event)事件
ex. (click).(deleteRequest)....

[(Two-way)]屬性與事件
ex. [(ngModel)]
